export const questions = [
    {
        id:1,
        question:'1fdsf',
        answer:'answer1'
    },
    {
        id:2,
        question:'1fdsfd',
        answer:'answer1'
    },
    {
        id:3,
        question:'1fgs',
        answer:'answer1'
    },
    {
        id:4,
        question:'1rethtrh',
        answer:'answer1'
    },
    {
        id:5,
        question:'1htrhtrh',
        answer:'answer1'
    },
    {
        id:6,
        question:'1htrhtr',
        answer:'answer1'
    },
];